### ISSUE TITLE
酷Q已挂...球dll+json的格式以换至mirai

### ISSUE THREAD

**Issue by xiaobaozi233** [yomunsam/EVEMarketBot#2]
感谢

**Comment by yomunsam** [comment]
没研究过mirai，打算去看看的时候发现项目好像已经没了，请问您知道哪有相关资料么，我去研究下怎么移植过去

**Comment by xiaobaozi233** [comment]
一键包：
[MiraiOK](https://github.com/LXY1226/MiraiOK)
酷Q插件兼容：
[mirai-native](https://github.com/iTXTech/mirai-native)

**Comment by yomunsam** [comment]
https://github.com/yomunsam/EVEMarketBot/releases/tag/3.0.6

反正，大概出了个版本试试.

我这边没成功，但是看起来插件已经被加载了，我估计Java环境啥的可能有点问题，我再琢磨琢磨

**Comment by xiaobaozi233** [comment]
可以参考一下mirai的文档
https://github.com/mamoe/mirai


https://github.com/mamoe/mirai/blob/master/docs/mirai.md


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yomunsam/EVEMarketBot"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午5:42
收件人:&nbsp;"yomunsam/EVEMarketBot"<EVEMarketBot@noreply.github.com&gt;;
抄送:&nbsp;"xiaobaozi"<xiaobaozi@miku.tw&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yomunsam/EVEMarketBot] 酷Q已挂...球dll+json的格式以换至mirai (#2)





 
https://github.com/yomunsam/EVEMarketBot/releases/tag/3.0.6
 
反正，大概出了个版本试试.
 
我这边没成功，但是看起来插件已经被加载了，我估计Java环境啥的可能有点问题，我再琢磨琢磨

**Comment by xiaobaozi233** [comment]
我尝试用[CQXQ](https://github.com/w4123/CQXQ)试了一下，可以正常使用了。
请问有没有办法能只显示欧服物价不显示国服物价？谢谢！

**Comment by yomunsam** [comment]
> [[CQXQ]，]](https://github.com/w4123/CQXQ)
> ◆！

目前没有这方面的设计

**Comment by silkynabs** [comment]
> 我尝试用[CQXQ](https://github.com/w4123/CQXQ)试了一下，可以正常使用了。
> 请问有没有办法能只显示欧服物价不显示国服物价？谢谢！

请问你是怎么用CQXQ成功运行的呀，我报错后不知道该把db文件放在哪

**Comment by xiaobaozi233** [comment]
> > 我尝试用[CQXQ](https://github.com/w4123/CQXQ)试了一下，可以正常使用了。
> > 请问有没有办法能只显示欧服物价不显示国服物价？谢谢！
> 
> 请问你是怎么用CQXQ成功运行的呀，我报错后不知道该把db文件放在哪

*\CQXQ\CQPlugins\config\evemarket.dll\
