### ISSUE TITLE
请问作者还会继续更新吗

### ISSUE THREAD

**Issue by silkynabs** [yomunsam/EVEMarketBot#3]
您好，我在尝试了您的mirai-native适配后，会报这样的错误
如果您不打算维护的话，可以不可以请您分享下之前适配酷q版本的cpk的dll和json呀，我打算用CQXQ尝试一下
现在酷q用不了了，我没法通过cpk获取dll，麻烦您了！

> 03:25:24 [INFO] [MiraiNative] [EVE市场姬 Debug] Sqlite Connect Str:Data Source=C:\Users\SilkyNabs\Desktop\Mirai\plugins\MiraiNative\data\io.nekonya.evemarket.bot\eve_static.db
A fatal error has been detected by the Java Runtime Environment:
Internal Error (0xe0434352), pid=16604, tid=0x00003218
JRE version: OpenJDK Runtime Environment (8.0_252-b09) (build 1.8.0_252-b09)
Java VM: OpenJDK Client VM (25.252-b09 mixed mode windows-x86 )
Problematic frame:
C  [KERNELBASE.dll+0x1146d2]
Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
An error report file with more information is saved as:
C:\Users\SilkyNabs\Desktop\Mirai\hs_err_pid16604.log
If you would like to submit a bug report, please visit:
  http://bugreport.java.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

**Comment by yomunsam** [comment]
原始dll在这儿，
https://github.com/yomunsam/EVEMarketBot/releases/tag/3.0.6

另一个Issues有人运行成功了

这个东西大概是不打算维护了，这套sdk为了兼容酷Q用了很老的东西，搞起来我也不太顺手。
直接基于Mirai的船新版本在路上了

**Comment by silkynabs** [comment]
没摸索出CQXQ那个怎么操作，但是搞定了mirai-native的报错问题，插件可以正常运行了，好耶.jpg
libiconv.dll和sqlite3.dll被CQHTTP依赖，但是MiraiNative下libraries里面并没有这两个文件，只需要把这俩文件放进文件夹里预先加载，报错问题就解决了
期待基于mirai的船新版本:P
